version: "3.3"
services:
    api:
      build: .
      depends_on:
        - mongo
      ports:
        - "3000:3000"
      network_mode: bridge
      links:
        - mongo

    mongo:
      image: mongo
      network_mode: bridge
      environment:
        MONGO_INITDB_DATABASE: quiz
      volumes:
        - ./data:/data/
      ports:
        - "27017:27017"
